[package]
name = "aggregator"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
connectors_common = { path = "../connectors/common" }
log = "0.4"
env_logger = "0.10"
serde = { version = "1.0", features = ["derive"] }
