[package]
name = "rust_hft_py"
version = "0.1.0"
edition = "2021"

[lib]
name = "hft_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
rust_core = { path = "../rust_core" }
serde_json = "1.0"
